[package]
name = "proxy"
version = "0.1.0"
authors = ["nt"]

[dependencies]
ctrlc = "3.1.1"
futures = "0.1.23"
libc = "0.2.42"
nix = "0.11.0"
tokio = "0.1.14"
tokio-current-thread = "0.1.4"
tk-listen = "0.2.0"
base64 = "0.9.2"